### ISSUE TITLE
Support specify the todo.org filename?

### ISSUE THREAD

**Issue by stardiviner** [danielma/magit-org-todos.el#1]
Can you add a `defcustom` for user to specify different filename?

**Comment by redblobgames** [comment]
Good idea. In the meantime I redefined this function:

```
(defun magit-org-todos--todo-file-path ()
  "Path of the todo file."
  (concat (magit-toplevel) "yourfilename.org"))
```

**Comment by stardiviner** [comment]
Yeah, use `defcustom` variable all over the code is a good solution.
