### ISSUE TITLE
Add items from source files?

### ISSUE THREAD

**Issue by alphapapa** [danielma/magit-org-todos.el#6]
Hi,

I just saw this package, and it looks really cool!  But what if it also added items from the source files?  Maybe it could use Jonas Bernoulli's hl-todo package to get the items or item types.  What do you think?  :)

**Comment by danielma** [comment]
🤔 that's a fascinating idea! 

A cursory google search led me to this package: https://github.com/WolfeCub/todo-projectile

Are you interested in looking for a way to make these two packages play nicely together? Use `todo-projectile` to create the `todo.org`, and `magit-org-todos` will show them in the magit status buffer!

**Comment by alphapapa** [comment]
Hm, that's an interesting idea too.  But I don't need an Org file with the items, I'd just like to display them directly in the Magit buffer.  The benefit of integration with `hl-todo` or `todo-projectile` would probably be to reuse their keyword configuration (although that might be of limited usefulness, as I wouldn't want `NOTE:` items in the Magit todo list).

Maybe this belongs in a separate package, then.  But I will surely learn from how you did it, as figuring out how to insert Magit sections would take a while on my own.  :)  Thanks.

**Comment by alphapapa** [comment]
https://github.com/alphapapa/magit-todos  What do you think?  :)

**Comment by danielma** [comment]
@alphapapa that is extremely cool! I love it! I'm going to install and try it out today
